# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Label')),
                ('text', models.TextField(verbose_name='Query')),
                ('is_private', models.BooleanField(default=True, help_text='Show query only to the selected user', verbose_name='Is private')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Last edition time')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Related model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['label'],
                'verbose_name': 'DjangoQL query',
                'verbose_name_plural': 'DjangoQL queries',
            },
        ),
    ]
